---
- name: setup boot environment for iso (iso creation = yes)
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
  - { name: 'debian-installer-launcher', state: 'present' }
  - { name: 'live-boot', state: 'present' }
  - { name: 'live-boot-initramfs-tools', state: 'present' }
  - { name: 'live-tools', state: 'present' }
  - { name: 'intel-microcode', state: 'absent' }
  when: chroot == true
  tags:
  - boot

- name: setup boot environment for system (iso creation = no)
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
  - { name: 'debian-installer-launcher', state: 'absent' }
  - { name: 'live-boot', state: 'absent' }
  - { name: 'live-boot-initramfs-tools', state: 'absent' }
  - { name: 'live-tools', state: 'absent' }
  - { name: 'intel-microcode', state: 'present' }
  when: chroot == false
  tags:
  - boot

- name: fix broken update-initramfs package (iso creation = no)
  shell: |
    if [ -f /usr/sbin/update-initramfs.orig.initrfs-tools ]; then
      mv /usr/sbin/update-initramfs.orig.initrfs-tools /usr/sbin/update-initramfs
      echo "changed"
    fi
  when: chroot == false
  register: fix_update_initramfs
  changed_when: fix_update_initramfs.stdout | search('changed')
  tags:
  - boot

- name: install essential packages (this may take a while)
  apt: name="{{ item }}"
  with_items:
  - build-essential
  - libelf-dev
  - libncurses5-dev
  - libssl-dev
  - unionfs-fuse
  tags:
  - boot

- name: install ubuntu casper packages (iso creation = yes)
  apt: name="{{ item }}"
  with_items:
  - casper
  - lupin-casper
  when: chroot == true and ansible_distribution == 'Ubuntu'
  tags:
  - boot

- name: remove ubuntu casper packages (iso creation = no)
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
  - casper
  - lupin-casper
  when: chroot == false and ansible_distribution == 'Ubuntu'
  tags:
  - boot

- name: remove unused kernels
  apt:
    name: linux-image-amd64
    state: absent
  failed_when: false
  tags:
  - boot

- name: create loop module config
  lineinfile:
    path: /etc/modprobe.d/loop.conf
    line: "options loop max_loop=8"
    create: yes
  tags:
  - boot

- name: add modules to initramfs
  lineinfile:
    path: /etc/initramfs-tools/modules
    line: "{{ item }}"
    create: yes
  with_items:
  - btusb
  - loop
  - overlay
  - pwm-lpss
  - pwm-lpss-platform
  - squashfs
  notify:
  - update boot
  tags:
  - boot
