---
- name: install bootstrap kernel (/boot)
  unarchive:
    src: files/bootstrap-kernel-boot.tar.bz2
    dest: /
  when: bootstrap is defined
  notify:
  - update boot
  tags:
  - boot

- name: check if distro uses /lib or /usr/lib
  stat:
    path: /lib
  register: lib_check

- name: install bootstrap kernel (/lib)
  unarchive:
    src: files/bootstrap-kernel-lib.tar.bz2
    dest: /
  when: bootstrap is defined and lib_check.stat.islnk is defined and lib_check.stat.islnk == False
  notify:
  - update boot
  tags:
  - boot

- name: install bootstrap kernel (/usr/lib)
  unarchive:
    src: files/bootstrap-kernel-lib.tar.bz2
    dest: /usr/
  when: bootstrap is defined and lib_check.stat.islnk is defined and lib_check.stat.islnk
  notify:
  - update boot
  tags:
  - boot

- name: fetch latest jwrdegoede kernel sources (this may take a while)
  git:
    repo: https://github.com/jwrdegoede/linux-sunxi.git
    dest: /usr/src/linux-jwrdegoede
    force: yes
    depth: 1
  when: bootstrap is not defined
  register: kernel_sources
  tags:
  - boot

- name: build new kernel (this may take a while)
  make:
    chdir: /usr/src/linux-jwrdegoede
    target: -j5
    params:
      LOCALVERSION: -jwrdegoede
  when: kernel_sources.changed and bootstrap is not defined
  tags:
  - boot

- name: remove old kernel versions
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
  - '/boot/*bootstrap*'
  - '/boot/*jwrdegoede*'
  - '/lib/modules/*bootstrap*'
  - '/lib/modules/*jwrdegoede*'
  - '/usr/lib/modules/*bootstrap*'
  - '/usr/lib/modules/*jwrdegoede*'
  when: kernel_sources.changed and bootstrap is not defined
  tags:
  - boot

- name: install kernel modules (this may take a while)
  make:
    chdir: /usr/src/linux-jwrdegoede
    target: modules_install
    params:
      LOCALVERSION: -jwrdegoede
  when: kernel_sources.changed and bootstrap is not defined
  tags:
  - boot

- name: install new kernel
  shell: cp -f /usr/src/linux-jwrdegoede/arch/x86/boot/bzImage /boot/vmlinuz-$(ls -t /lib/modules/ |head -n 1)
  args:
    executable: /bin/bash
    warn: false
  notify:
  - update boot
  when: kernel_sources.changed and bootstrap is not defined
  tags:
  - boot

- name: clean up kernel build directory
  make:
    chdir: /usr/src/linux-jwrdegoede
    target: clean
  when: kernel_sources.changed and bootstrap is not defined
  tags:
  - boot

- include: arch.yml
  when: ansible_distribution == 'Antergos' or ansible_distribution == 'Archlinux' or ansible_distribution == 'Manjaro Linux'

- include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Kali' or ansible_distribution == 'Linuxmint' or ansible_distribution == 'Ubuntu'

- include: fedora.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Fedora' or ansible_distribution == 'RedHat'

- include: gentoo.yml
  when: ansible_distribution == 'Gentoo'

- name: set grub boot options
  lineinfile:
    path: /etc/default/grub
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
    create: yes
  with_items:
  - { key: 'GRUB_CMDLINE_LINUX_DEFAULT', value: '' }
  - { key: 'GRUB_DEFAULT', value: 'saved' }
  - { key: 'GRUB_TIMEOUT', value: '2' }
  notify:
  - update boot
  tags:
  - boot
