---
- name: install essential packages (this may take a while)
  package: name="{{ item }}"
  with_items:
  - ibus
  - libXrandr
  - xinput_calibrator
  - xorg-x11-drv-intel
  tags:
  - xorg

- name: install touchegg (this may take a while)
  apt: name="{{ item }}"
  with_items:
  - touchegg
  tags:
  - xorg
