---
- name: install essential packages (this may take a while)
  pacman: name="{{ item }}"
  with_items:
  - ibus
  - libva-intel-driver
  - mesalib
  - xorg-driver-video-intel
  - xinput
  - xrandr
  tags:
  - xorg
