---
- name: update initrd
  shell: |
    # determine new kernel version
    KERNEL_VERSION=$(ls -t /lib/modules/ |grep 'bootstrap\|jwrdegoede' |head -n 1)
    
    # recreate initramfs image
    if [ -f /usr/sbin/update-initramfs ]; then
      update-initramfs -c -k ${KERNEL_VERSION} || update-initramfs -u -k ${KERNEL_VERSION}
    elif [ -f /usr/bin/dracut ]; then
      dracut -f /boot/initrd.img-${KERNEL_VERSION} ${KERNEL_VERSION}
    elif [ -f /usr/bin/mkinitcpio ]; then
      mkinitcpio -c /etc/mkinitcpio.conf -g /boot/initrd.img-${KERNEL_VERSION} -k ${KERNEL_VERSION} || true
    else
      echo "I can't build a new initramfs - this is bad!"
      exit 1
    fi
  register: updateinitrd
  failed_when: updateinitrd.rc != 0
  listen: update boot

- name: update grub
  shell: |
    # Update grub config
    if which grub-mkconfig; then
      grub-mkconfig -o /boot/grub/grub.cfg
    elif which grub2-mkconfig; then
      grub2-mkconfig -o /boot/grub/grub.cfg
    else
      echo "I can't update grub config - this is bad!"
      exit 1
    fi
  when: chroot == false
  register: updategrub
  failed_when: updategrub.rc != 0
  listen: update boot
